sudo: false
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - python setup.py install
script:
  - flake8 rail_gun
  - black rail_gun
  - bandit rail_gun
after_success:
  - codecov -e $TRAVIS_PYTHON_VERSION
